export const SEARCH_UPDATE = 'SEARCH_UPDATE';
export const CURRENT_SEARCH = 'CURRENT_SEARCH';
export const SAVE_DATA = 'SAVE_DATA';
export const SET_CODEMIRROR = 'SET_CODEMIRROR';
export const CODEMIRROR_UPDATE = 'CODEMIRROR_UPDATE';